/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as MyAppointmentRouteImport } from './routes/my-appointment'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin/appointments'
import { Route as AuthenticatedAdminArchiveRouteImport } from './routes/_authenticated/admin/archive'
import { Route as AuthenticatedAdminAvailabilityRouteImport } from './routes/_authenticated/admin/availability'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminMechanicsRouteImport } from './routes/_authenticated/admin/mechanics'
import { Route as AuthenticatedAdminMotorcyclesRouteImport } from './routes/_authenticated/admin/motorcycles'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPartsRouteImport } from './routes/_authenticated/admin/parts'
import { Route as AuthenticatedAdminPricesRouteImport } from './routes/_authenticated/admin/prices'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminScheduleBlocksRouteImport } from './routes/_authenticated/admin/schedule-blocks'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppointmentRoute = MyAppointmentRouteImport.update({
  id: '/my-appointment',
  path: '/my-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArchiveRoute =
  AuthenticatedAdminArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAvailabilityRoute =
  AuthenticatedAdminAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMechanicsRoute =
  AuthenticatedAdminMechanicsRouteImport.update({
    id: '/mechanics',
    path: '/mechanics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMotorcyclesRoute =
  AuthenticatedAdminMotorcyclesRouteImport.update({
    id: '/motorcycles',
    path: '/motorcycles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartsRoute = AuthenticatedAdminPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPricesRoute =
  AuthenticatedAdminPricesRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScheduleBlocksRoute =
  AuthenticatedAdminScheduleBlocksRouteImport.update({
    id: '/schedule-blocks',
    path: '/schedule-blocks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/my-appointment': typeof MyAppointmentRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/mechanics': typeof AuthenticatedAdminMechanicsRoute
  '/admin/motorcycles': typeof AuthenticatedAdminMotorcyclesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parts': typeof AuthenticatedAdminPartsRoute
  '/admin/prices': typeof AuthenticatedAdminPricesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/schedule-blocks': typeof AuthenticatedAdminScheduleBlocksRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/my-appointment': typeof MyAppointmentRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/mechanics': typeof AuthenticatedAdminMechanicsRoute
  '/admin/motorcycles': typeof AuthenticatedAdminMotorcyclesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parts': typeof AuthenticatedAdminPartsRoute
  '/admin/prices': typeof AuthenticatedAdminPricesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/schedule-blocks': typeof AuthenticatedAdminScheduleBlocksRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/my-appointment': typeof MyAppointmentRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/_authenticated/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/mechanics': typeof AuthenticatedAdminMechanicsRoute
  '/_authenticated/admin/motorcycles': typeof AuthenticatedAdminMotorcyclesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/parts': typeof AuthenticatedAdminPartsRoute
  '/_authenticated/admin/prices': typeof AuthenticatedAdminPricesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/schedule-blocks': typeof AuthenticatedAdminScheduleBlocksRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/my-appointment'
    | '/services'
    | '/shop'
    | '/admin'
    | '/admin/appointments'
    | '/admin/archive'
    | '/admin/availability'
    | '/admin/customers'
    | '/admin/mechanics'
    | '/admin/motorcycles'
    | '/admin/notifications'
    | '/admin/parts'
    | '/admin/prices'
    | '/admin/reports'
    | '/admin/schedule-blocks'
    | '/admin/services'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/my-appointment'
    | '/services'
    | '/shop'
    | '/admin/appointments'
    | '/admin/archive'
    | '/admin/availability'
    | '/admin/customers'
    | '/admin/mechanics'
    | '/admin/motorcycles'
    | '/admin/notifications'
    | '/admin/parts'
    | '/admin/prices'
    | '/admin/reports'
    | '/admin/schedule-blocks'
    | '/admin/services'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/my-appointment'
    | '/services'
    | '/shop'
    | '/_authenticated/admin'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/archive'
    | '/_authenticated/admin/availability'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/mechanics'
    | '/_authenticated/admin/motorcycles'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/parts'
    | '/_authenticated/admin/prices'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/schedule-blocks'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  MyAppointmentRoute: typeof MyAppointmentRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-appointment': {
      id: '/my-appointment'
      path: '/my-appointment'
      fullPath: '/my-appointment'
      preLoaderRoute: typeof MyAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/archive': {
      id: '/_authenticated/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AuthenticatedAdminArchiveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/availability': {
      id: '/_authenticated/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AuthenticatedAdminAvailabilityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mechanics': {
      id: '/_authenticated/admin/mechanics'
      path: '/mechanics'
      fullPath: '/admin/mechanics'
      preLoaderRoute: typeof AuthenticatedAdminMechanicsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/motorcycles': {
      id: '/_authenticated/admin/motorcycles'
      path: '/motorcycles'
      fullPath: '/admin/motorcycles'
      preLoaderRoute: typeof AuthenticatedAdminMotorcyclesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parts': {
      id: '/_authenticated/admin/parts'
      path: '/parts'
      fullPath: '/admin/parts'
      preLoaderRoute: typeof AuthenticatedAdminPartsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prices': {
      id: '/_authenticated/admin/prices'
      path: '/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AuthenticatedAdminPricesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schedule-blocks': {
      id: '/_authenticated/admin/schedule-blocks'
      path: '/schedule-blocks'
      fullPath: '/admin/schedule-blocks'
      preLoaderRoute: typeof AuthenticatedAdminScheduleBlocksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminArchiveRoute: typeof AuthenticatedAdminArchiveRoute
  AuthenticatedAdminAvailabilityRoute: typeof AuthenticatedAdminAvailabilityRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminMechanicsRoute: typeof AuthenticatedAdminMechanicsRoute
  AuthenticatedAdminMotorcyclesRoute: typeof AuthenticatedAdminMotorcyclesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPartsRoute: typeof AuthenticatedAdminPartsRoute
  AuthenticatedAdminPricesRoute: typeof AuthenticatedAdminPricesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminScheduleBlocksRoute: typeof AuthenticatedAdminScheduleBlocksRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminArchiveRoute: AuthenticatedAdminArchiveRoute,
  AuthenticatedAdminAvailabilityRoute: AuthenticatedAdminAvailabilityRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminMechanicsRoute: AuthenticatedAdminMechanicsRoute,
  AuthenticatedAdminMotorcyclesRoute: AuthenticatedAdminMotorcyclesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPartsRoute: AuthenticatedAdminPartsRoute,
  AuthenticatedAdminPricesRoute: AuthenticatedAdminPricesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminScheduleBlocksRoute: AuthenticatedAdminScheduleBlocksRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  MyAppointmentRoute: MyAppointmentRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
